version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: qurilish_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: qurilish_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./database/init-prod.sql:/docker-entrypoint-initdb.d/01-init.sql

volumes:
  postgres_data_prod:
